"""Constants for Yahoo Finance sensor."""

ATTR_FIFTY_DAY_AVERAGE = "fiftyDayAverage"
ATTR_FIFTY_DAY_SYMBOL = "symbol"
ATTR_PREVIOUS_CLOSE = "previousClose"
ATTRIBUTION = "Data provided by Yahoo Finance"
BASE = "https://query1.finance.yahoo.com/v7/finance/quote?symbols="
CONF_SYMBOLS = "symbols"
DEFAULT_CURRENCY = "USD"
DEFAULT_ICON = "mdi:currency-usd"
DOMAIN = "yahoofinance"