# Limited configuration instead of default_config
# https://github.com/home-assistant/core/tree/dev/homeassistant/components/default_config
automation:
frontend:
history:
logbook:

logger:
  default: info
  logs:
    custom_components.yahoofinance: debug

yahoofinance:
  show_trending_icon: true
  show_currency_symbol_as_unit: true

  #Interval too small - will throw an error
  #scan_interval: 30

  #Update disabled
  #scan_interval: "manual"

  scan_interval: 45

  symbols:
    - symbol: "0P00008F5Y.L"
    - symbol: GBPUSD=X
      no_unit: true
    - symbol: IDFCBANK.BO
    - symbol: baba
      target_currency: inr
      #scan_interval: 30
    - symbol: ^SSMI
      no_unit: true
    - symbol: EMIM.L
      target_currency: EUR
      scan_interval: 30
    - symbol: AAPL
    - symbol: USDINR=X
      #scan_interval: 45
    - symbol: ADYEN.AS
      #scan_interval: "none"
